// get address-
export const GET_ADDRESS_REQUEST="GET_ADDRESS_REQUEST"
export const GET_ADDRESS_SUCCESS="GET_ADDRESS_SUCCESS"
export const GET_ADDRESS_ERROR="GET_ADDRESS_ERROR"


// add address-
export const ADD_ADDRESS_REQUEST="ADD_ADDRESS_REQUEST"
export const ADD_ADDRESS_SUCCESS="ADD_ADDRESS_SUCCESS"
export const ADD_ADDRESS_ERROR="ADD_ADDRESS_ERROR"


// updata address-
export const UPDATE_ADDRESS_REQUEST="UPDATE_ADDRESS_REQUEST"
export const UPDATE_ADDRESS_SUCCESS="UPDATE_ADDRESS_SUCCESS"
export const UPDATE_ADDRESS_ERROR="UPDATE_ADDRESS_ERROR"
