export const REGISTER_START = "REGISTER_START"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"


export const GET_LOGIN_REQUEST="GET_LOGIN_REQUEST"
export const GET_LOGIN_SUCCESS="GET_LOGIN_SUCCESS"
export const GET_LOGIN_ERROR="GET_LOGIN_ERROR"